In [1]:
import pandas as pd
from pycaret.datasets import get_data
from pycaret.classification import *
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("../../output/clustered_data.csv")
df

,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Cluster
0,Grass,Poison,318,45,49,49,65,65,45,1,0,Cluster 0
1,Grass,Poison,405,60,62,63,80,80,60,1,0,Cluster 3
2,Grass,Poison,525,80,82,83,100,100,80,1,0,Cluster 1
3,Grass,Poison,625,80,100,123,122,120,80,1,0,Cluster 2
4,Fire,NaN,309,39,52,43,60,50,65,1,0,Cluster 0
...,...,...,...,...,...,...,...,...,...,...,...,...
795,Rock,Fairy,600,50,100,150,100,150,50,6,1,Cluster 2
796,Rock,Fairy,700,50,160,110,160,110,110,6,1,Cluster 2
797,Psychic,Ghost,600,80,110,60,150,130,70,6,1,Cluster 2
798,Psychic,Dark,680,80,160,60,170,130,80,6,1,Cluster 2
799,Fire,Water,600,80,110,120,130,90,70,6,1,Cluster 2

In [3]:
df.columns

Index(['Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Cluster'],
      dtype='object')

In [4]:
setup(data=df, target="Cluster")

In [5]:
best_model = compare_models()

In [12]:
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦

In [6]:
predict_model(best_model)

,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Cluster,prediction_label,prediction_score
94,Water,Ice,475,90,70,80,70,95,70,1,0,Cluster 1,Cluster 1,1.0
770,Fairy,NaN,525,95,65,65,110,130,60,6,0,Cluster 1,Cluster 1,1.0
150,Rock,Water,495,70,60,125,115,70,55,1,0,Cluster 1,Cluster 1,1.0
554,Grass,NaN,308,45,45,55,45,55,63,5,0,Cluster 0,Cluster 0,1.0
88,Electric,Steel,325,25,35,70,95,55,45,1,0,Cluster 0,Cluster 0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783,Ghost,Grass,335,59,66,70,44,55,41,6,0,Cluster 0,Cluster 0,1.0
620,Dark,Fighting,348,50,75,70,35,70,48,5,0,Cluster 3,Cluster 3,1.0
638,Psychic,NaN,290,45,30,40,105,50,20,5,0,Cluster 0,Cluster 0,1.0
194,Electric,NaN,365,70,55,55,80,60,45,2,0,Cluster 3,Cluster 3,1.0
758,Rock,Water,306,42,52,67,39,56,50,6,0,Cluster 0,Cluster 0,1.0

In [8]:
save_model(best_model,'classification_model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('label_encoding',
                  TransformerWrapperWithInverse(exclude=None, include=None,
                                                transformer=LabelEncoder())),
                 ('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Total', 'HP', 'Attack', 'Defense',
                                              'Sp. Atk', 'Sp. Def', 'Speed',
                                              'Generation', 'Legendary'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,...
                                     transformer=CleanColumnNames(match='[\\]\\[\\,\\{\\}\\"\\:]+'))),
                 ('trained_model',
                  DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                         criterion='gini', max_depth=None,
                                         max_features=None, max_leaf_nodes=None,
                                         min_impurity_decrease=0.0,
                                         min_samples_leaf=1, min_samples_split=2,
                                         min_weight_fraction_leaf=0.0,
                                         monotonic_cst=None, random_state=5007,
                                         splitter='best'))],
          verbose=False),
 'classification_model.pkl')